
prefix = "."
guild_id = 689534383878701223
bot_id = 550474149332516881

[developers]
    razi = 159516156728836097
    basil = 206430272671973377






#+
#+ --- Channels
#+
[logs]
    bot = 1020904525013463120
    server = 833960569941393438
    messages = 833960665403883550
    staff = 1070960923587645481
    adult = 1169718858714710107
    coins = 1046684571728625674


[channels]
    welcome = 1238725736211152926
    general = 1158984202646208533
    roles = 1203964036203548692
    rules = 1239858476243615804
    store = 946730953731100682
    politics = 1202139470326149201
    leaderboard = 929093224545550336






#+  
#+ --- Roles 
#+ 
[access_roles]
    alive = 1154236618606125106
    dead = 1240429252675899432

[age_roles]
    adult = 1093881864806223932
    underage = 1109752142878744627

[seperator_roles]
    access = 1204290817527779408
    purchases = 1069865335689330769
    pings = 1028802118188028005
    about = 1070968239644999681

[purchase_roles]
    image_pass = 1050588443283042334
    library_pass = 1029965266391679037
    soundboard_pass = 1137618537020665910
    stats_channel_access = 1051035273330442270
    threads_perm = 1186717217501487225
    external_emojis = 1186714489022849034

[ping_roles]
    changelogs = 1054142893872398346
    voters = 1168438948226416701
    events = 1116079160398454889
    welcomer = 1134574155828838560

[dm_roles]
    open = 1133384245834960957
    ask = 1133385949540270080
    closed = 1133384223592546315


#+
#+ --- Emojis
#+
[emojis]
    coin = "<:Coin:1026302157521174649>"
    nitro = "<:Nitro:1095491689029849189>"




#+
#+ --- Messages
#+
[purgatory_banners]
    welcome_id = 1239078912399773737 
    welcome_url = "https://cdn.discordapp.com/attachments/550556052396179458/1239762951376732271/LaKmL2t.png?ex=66441ab9&is=6642c939&hm=f3220b723e9c91fe94bb322251be92969124c5348cbf52c6b339a64d0ac7a5de&"
    tos_id = 1239078928522678272 
    tos_url = "https://cdn.discordapp.com/attachments/550556052396179458/1239449567762583593/Uw2RnmE.png?ex=6642f6dc&is=6641a55c&hm=4637de5524118295f45d400621cd986821f4cb66265d269a1a27172714debe8d&"
    verify_id = 1239078944020631623
    verify_url = "https://cdn.discordapp.com/attachments/550556052396179458/1239845283312046111/nGopsMt.png?ex=66446766&is=664315e6&hm=92194c30ff9fdb9a285bca351ea285bd1febcd0bc85f1cd897ae54286d32d18d&"
    etiquette_id = 1239887374956101662
    etiquette_url = "https://cdn.discordapp.com/attachments/550556052396179458/1239883592046346250/WGCLmSq.png?ex=66448b14&is=66433994&hm=54812e21d6a26b97742a40caaa0e1121a039e51b4e7b34c06fc176ec518e46e7&"
    respect_id = 1239887386310082601
    respect_url = "https://cdn.discordapp.com/attachments/550556052396179458/1239891494618267658/W4Ud8Ip.png?ex=66449270&is=664340f0&hm=6be65c90dd169943f2a0ad25badda83a55a8dd5e75439604d21be7931e4dd23f&"
    society_id = 1239887415297179698
    society_url = "https://cdn.discordapp.com/attachments/550556052396179458/1240141200464416788/IxdbZ4D.png?ex=66457afe&is=6644297e&hm=fed741e1809725992a74e204e39e6aea59be4d25ca4d7fad5a9516232c701573&"
    council_id = 1239887430115397683
    council_url = "https://cdn.discordapp.com/attachments/550556052396179458/1240150622616162374/qiFt3TM.png?ex=664583c5&is=66443245&hm=9742ef16b5ff8ece2f71386f2afe5265c9b46018e06e5778a3b97f64a34f8fdd&"

[welcome_messages]
    1 = 1239078921371123764
    2 = 1239078937309483038
    3 = 1239078948332113975

[roles_messages]
    1 = 1209328523328622632
    2 = 1209328531780407397
    3 = 1209328538621313074
    4 = 1209328547076771930
    5 = 1209328551979909183
    6 = 1209328557302480946

[rules_messages]
    1 = 1239887381033910345
    2 = 1239887406212321292
    3 = 1239887422322638919
    4 = 1239887437262622720

[store_messages]
    1 = 1209329229423186000
    2 = 1209329233466232912
    3 = 1209329237048295445
    4 = 1209329240831696997
    5 = 1209329244237471815
    6 = 1209329247211225139

[leaderboard_messages]
    1 = 1233063279249719408
    2 = 1233063295968219136
    3 = 1233063304029536276
    4 = 1233063313978425514
    5 = 1233078799441330316
    6 = 1233078814008152127
    7 = 1233086187523281051
    8 = 1233086196675252414
    9 = 1233091139003748474
    10 = 1233091146016886785